name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Download EasyX installer
      run: curl -L -o EasyX.exe https://easyx.cn/download/EasyX_20240601.exe

    - name: Install 7zip
      run: choco install 7zip -y

    - name: Extract EasyX installer
      run: |
        mkdir easyx
        7z x EasyX.exe -oeasyx

        if (!(Test-Path easyx/include) -or !(Test-Path easyx/lib)) {
          Write-Error "Include or Lib folder not found in extracted EasyX files."
          exit 1
        }
        
        xcopy easyx\include\ 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include\' /s /e
        xcopy easyx\lib\VC2015\x64\ 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\lib\x64\' /s /e

    - name: Install clang-format
      run: choco install llvm -y

    - name: Check and format code with clang-format
      run: |
        clang-format --version
        clang-format -i -style=file src/*.cpp src/*.h
        git diff --exit-code

    - name: Build project with MSBuild
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
